# Q5: Collatz Conjecture Analysis

def collatz_rec(n, seq=None):
    """Recursive version: returns the list of steps taken to reach 1."""
    if seq is None: 
        seq = []
    seq.append(n)
    
    if n == 1:
        return seq
    
    # If even: n/2 | If odd: 3n+1
    if n % 2 == 0:
        return collatz_rec(n // 2, seq)
    else:
        return collatz_rec(3 * n + 1, seq)

def collatz_while(n):
    """While loop version: returns the list of steps taken to reach 1."""
    seq = []
    temp_n = n
    while temp_n != 1:
        seq.append(temp_n)
        if temp_n % 2 == 0:
            temp_n //= 2
        else:
            temp_n = 3 * temp_n + 1
    seq.append(1)
    return seq

# --- Main Execution ---

# 1. Print sequence for a user-given number
val = int(input("Enter a number: "))
print(f"Full sequence for {val}: {collatz_rec(val)}")

# 2. Find which number 1-50 takes the most steps
max_steps = 0
best_num = 0

for i in range(1, 51):
    # Using the recursive function to find the sequence
    # Steps = Total numbers in sequence minus the starting number
    current_seq = collatz_rec(i, seq=None) 
    steps = len(current_seq) - 1
    
    if steps > max_steps:
        max_steps = steps
        best_num = i

print("-" * 30)
print(f"Number between 1-50 with most steps: {best_num}")
print(f"Total step count: {max_steps}")
print("-" * 30)

# 3. Verify both versions produce identical sequences for 5 inputs
test_inputs = [7, 15, 27, 42, 49]
print("Verifying Recursive vs While Loop:")

all_match = True
for t in test_inputs:
    # Compare the lists generated by both functions
    if collatz_rec(t, seq=None) == collatz_while(t):
        print(f"Input {t:2}: MATCH ✅")
    else:
        print(f"Input {t:2}: MISMATCH ❌")
        all_match = False

if all_match:
    print("\nVerification Successful: Both methods are identical.")

